development:
  adapter: postgresql
  encoding: unicode
  database: drinkster_development
  pool: 5
  username: daviskoh
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: drinkster_test
  pool: 5
  username: daviskoh
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: drinkster_production
  pool: 5
  username: daviskoh
  password:
